# This environment definition contains all a basic environment definition that
# is suitable for submitting scripts from the hi-ml-azure folder.
name: himl-azure
dependencies:
  - pip=21.2.4
  - python=3.10.4
