# This environment definition contains all packages to run hi-ml and hi-ml-azure development work, building and
# testing
name: himl
channels:
  - defaults
  - pytorch
dependencies:
  - pip=21.2.4
  - python=3.10.4
  - pytorch=1.10.0
  - cudatoolkit=11.3.1
  - pip:
      - -r ../hi-ml-azure/run_requirements.txt
      - -r run_requirements.txt
      - -r ../build_requirements.txt
      - -r ../test_requirements.txt
