name: Multimodal PR
on:
  push:
    branches: [ main ]
    tags:
      - '*'
  pull_request:
    branches: [ main ]
    paths:
      - "multimodal/**"
      - ".github/workflows/multimodal-pr.yml"

env:
  pythonVersion: 3.7
  folder: multimodal

jobs:

  flake8:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Set up Python ${{ env.pythonVersion }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.pythonVersion }}

      - name: flake8
        run: |
          cd ${{ env.folder }}
          make pip_test
          make flake8

  mypy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Set up Python ${{ env.pythonVersion }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.pythonVersion }}

      - name: mypy
        run: |
          cd ${{ env.folder }}
          make pip_test
          make mypy

  pytest:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Set up Python ${{ env.pythonVersion }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.pythonVersion }}

      - name: Upgrade PIP
        run: |
          cd ${{ env.folder }}
          make pip_upgrade

      - name: Test with pytest
        run: |
          cd ${{ env.folder }}

          # Run tests
          make pip
          make pytest

      - name: Run Jupyter notebooks
        run: |
          cd ${{ env.folder }}
          make notebooks

  publish:
    runs-on: ubuntu-18.04
    needs: [ flake8, mypy, pytest ]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Set up Python ${{ env.pythonVersion }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.pythonVersion }}

      - name: Install pypa/build
        run: pip install build

      - name: Build a binary wheel and a source tarball
        run: python -m build --sdist --wheel --outdir ${{ env.folder }}/dist/ ${{ env.folder }}

      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.TEST_PIPY_TOKEN }}
          packages_dir: ${{ env.folder }}/dist/
          repository_url: https://test.pypi.org/legacy/
          verbose: true
          skip_existing: true

      - name: Publish package to PyPI
        if: "!startsWith(github.ref, 'refs/tags/v')"
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          packages_dir: ${{ env.folder }}/dist/
          verbose: true
